# Copyright (c) 2026 2026 Snover International Consulting LLC. All rights reserved.
# Licensed under the MIT License. See LICENSE file in the project root.

@{
    RootModule        = 'AITriad.psm1'
    ModuleVersion     = '0.8.6'
    GUID              = 'a7c3e1f0-4b2d-4e8a-9f6c-1d3b5e7a9c0f'
    Author            = 'Jeffrey Snover'
    CompanyName       = 'Snover International Consulting LLC'
    Copyright         = '(c) 2026 Snover International Consulting LLC. All rights reserved.'
    Description       = 'AI Triad Research — taxonomy queries, document ingestion, POV analysis'
    PowerShellVersion = '7.0'

    # Functions exported from this module
    FunctionsToExport = @(
        'Get-Tax'
        'Update-TaxEmbeddings'
        'Import-AITriadDocument'
        'Invoke-POVSummary'
        'Invoke-BatchSummary'
        'Find-Conflict'
        'Find-AITSource'
        'Save-WaybackUrl'
        'Save-AITSource'
        'Invoke-PIIAudit'
        'Update-Snapshot'
        'Show-TaxonomyEditor'
        'Show-POViewer'
        'Show-SummaryViewer'
        'Show-AITriadHelp'
        'Get-TaxonomyHealth'
        'Measure-TaxonomyBaseline'
        'Invoke-TaxonomyProposal'
        'Compare-Taxonomy'
        'Get-AITSource'
        'Get-AITDebate'
        'Repair-PovDescriptions'
        'Repair-PovLineage'
        'Repair-PovAttributes'
        'Export-AggregatedCruxes'
        'Get-Summary'
        'Invoke-AttributeExtraction'
        'Invoke-EdgeDiscovery'
        'Get-GraphNode'
        'Find-GraphPath'
        'Approve-Edge'
        'Approve-TaxonomyProposal'
        'Get-Edge'
        'Set-Edge'
        'Invoke-GraphQuery'
        'Get-ConflictEvolution'
        'Export-TaxonomyToGraph'
        'Install-GraphDatabase'
        'Invoke-CypherQuery'
        'Show-GraphOverview'
        'Get-TopicFrequency'
        'Get-IngestionPriority'
        'Find-SituationCandidates'
        'Find-CrossCuttingCandidates'
        'Show-TriadDialogue'
        'Register-AIBackend'
        'Install-AITriadData'
        'Install-AIDependencies'
        'Test-Dependencies'
        'Find-PossibleFallacy'
        'Find-PolicyAction'
        'Get-Policy'
        'Update-PolicyRegistry'
        'Show-FallacyInfo'
        'Test-TaxonomyIntegrity'
        'Invoke-HierarchyProposal'
        'Set-TaxonomyHierarchy'
        'Invoke-SchemaMigration'
        'Invoke-PolicyRefinement'
        'Repair-UnmappedConcepts'
        'Invoke-AITDebate'
        'Resume-AITDebate'
        'Convert-DebateToAudio'
        'Convert-MD2PDF'
        'Show-Markdown'
        'Show-DebateDiagnostics'
        'Repair-DebateOutput'
        'Show-DebateHarvest'
        'Get-AITSBOM'
        'Test-OntologyCompliance'
        'Get-RelevantTaxonomyNodes'
        'Invoke-QbafConflictAnalysis'
        'Test-ExtractionQuality'
        'Show-WorkflowRunner'
        'Test-EdgeDirection'
        'Test-AITJudgeModel'
        'Repair-AITSummaryMappings'
        'Repair-ResolvedBackfill'
        'Invoke-EdgeWeightEvaluation'
        'Repair-Markdown'
        'Compare-DebateRuns'
        'Compare-DebateQuality'
        'Measure-DebateQuality'
        'Invoke-DebateAB'
        'Show-OSSLicenses'
        'Get-FlightRecorderDump'
        'Get-AzureFlightRecorder'
        'Show-FlightRecorder'
        'Update-AITSourceIndex'
        'Get-PovLineage'
        'Get-IntellectualLineage'
        'Invoke-BDIWeightAssignment'
        'Register-AITriadDrive'
        'Get-TaxonomyProcess'
        'Request-FlightRecorderDump'
        'Get-FlightRecorderReport'
        'Get-AITClaim'
        'Compare-EmbeddingModel'
        'Test-RerankerBaseline'
        'New-SyntheticCorpus'
        'Update-SyntheticCorpus'
        'Sync-SyntheticCorpus'
        'Export-SyntheticEmbeddings'
        'Test-SynthesisCompleteness'
        'Get-ImportReport'
        'Get-CalibrationTrend'
        'Test-TaxEditorHealth'
        'Test-TaxEditorEndpoints'
        'Test-AnonymousDebateFlow'
        'Test-PersonaEndpoints'
        'Test-ServiceWorkerHealth'
        'Watch-DebateProgress'
        'Invoke-DebateBatch'
        'Get-FreeTierStatus'
        'Invoke-TaxEditorSmokeTest'
        'Test-AzureHealth'
        'Test-GitHubHealth'
        'Get-TaxEditorRevision'
        'Switch-TaxEditorRevision'
        'Get-TaxEditorDataCommit'
        'Undo-TaxEditorDataCommit'
        'Sync-TaxEditorData'
        'Reset-TaxEditorSession'
        'Get-TaxEditorImage'
        'Deploy-TaxEditorImage'
        'Set-TaxEditorKnownGood'
        'Restore-TaxEditorKnownGood'
        'Test-TaxEditorInfra'
        'Deploy-TaxEditorInfra'
        'Get-TaxEditorBlob'
        'Restore-TaxEditorBlob'
        'Get-CriticalInteraction'
        'Test-CriticalInteractions'
        'Merge-FlightRecorderDumps'
        'Get-TriadConfig'
        'Set-TriadConfig'
        'Invoke-TriadConfigReload'
        'Invoke-VernacularBatch'
        # t/1224 — Organization data model
        'Get-Organization'
        'Find-OrganizationByPOV'
        'Find-OrganizationByTopic'
        'Get-OrganizationStakeholders'
        'Import-Organization'
        'Compare-OrganizationPositions'
        # t/1526 — Organization actor-relationship edges
        'Get-OrganizationEdge'
        'Import-OrganizationEdge'
        # t/1261 — UsageID registry
        'Invoke-AIByUsage'
        # t/1308 — cc→sit migration
        'Invoke-CcToSitMigration'
        'Test-AIApiKey'
        # t/1492 — GHCR cleanup
        'Remove-StaleContainerImages'
        # t/1493 — Taxonomy snapshot fetch
        'Get-TaxonomySnapshot'
        # t/1498 — ACA revision queries
        'Get-ContainerAppRevision'
        # t/1499 — GH workflow run queries
        'Get-GitHubWorkflowRun'
        # t/1550 — POV aphorism backfill
        'Invoke-AphorismBatch'
        # t/1553 Stage 0 — org PUBLISHED edge seeding
        'Invoke-OrgPublishedSeeding'
        # t/1553 Stage 1 — org stance claim extraction
        'Invoke-OrgStanceExtraction'
        # t/1553 Stages 2+3 — claim→node matching + edge proposal aggregation
        'Invoke-OrgClaimMatching'
        # t/1560 Stage 5 — R2 rollup, per-camp derived alignment from approved edges
        'Invoke-OrgDerivedCampScores'
    )

    # Aliases exported from this module
    AliasesToExport   = @(
        'Import-Document'
        'Install-AITdependencies'
        'TaxonomyEditor'
        'POViewer'
        'SummaryViewer'
        'Redo-Snapshots'
        'Show-MD'
        'Workflow'
    )

    # Cmdlets exported (none — pure script module)
    CmdletsToExport   = @()

    # Variables exported (none)
    VariablesToExport = @()

    # Format files to load
    FormatsToProcess  = @('Formats/Taxonomy.Format.ps1xml')

    # Private data
    PrivateData = @{
        PSData = @{
            Tags       = @('AI', 'Taxonomy', 'Research', 'POV', 'Gemini')
            ProjectUri = 'https://github.com/jsnov/ai-triad-research'
        }
    }
}
