// Copyright (c) 2026 Jeffrey Snover. All rights reserved.
// Licensed under the MIT License. See LICENSE file in the project root.

import fs from 'fs/promises';
import { resolveDataPath } from '../config.js';
import { ActionableError } from '../../../../lib/debate/errors.js';
import { getGlobalRecorder } from '../../../../lib/flight-recorder/index.js';
import { getBackend } from './fileIO.js';

/**
 * Sole sanctioned reader for data-root files. Resolves relPath via
 * resolveDataPath() internally — callers pass a relative path, never absolute.
 *
 * Guard: absent or empty files always throw ActionableError and emit a
 * data_read_empty FR event — never silently return empty. opts.validate? runs
 * after the read; a throw from the validator triggers the same loud path.
 * Empty/missing alone would not catch a stale/short file — that was t/3085;
 * callers of size-sensitive data (e.g. embeddings) pass `validate` to assert
 * shape/count.
 */
export async function readDataFile(
  relPath: string,
  opts?: { largeFile?: true; validate?: (buf: Buffer) => void },
): Promise<Buffer> {
  const absPath = resolveDataPath(relPath);
  let buf: Buffer;

  if (opts?.largeFile) {
    try {
      // large-file: read local cache
      // Raw fs bypasses the storage backend; 63 MB embeddings.json exceeds the
      // GitHub Contents API 1 MB limit so the backend cannot serve it directly.
      buf = await fs.readFile(absPath);
    } catch (err: unknown) {
      const isEnoent = (err as NodeJS.ErrnoException).code === 'ENOENT';
      getGlobalRecorder()?.record({
        type: 'data_read_empty',
        component: 'read-data-file',
        level: 'error',
        message: `readDataFile: ${isEnoent ? 'missing' : 'read error'}: ${relPath}`,
        data: { relPath, absPath, error: String(err) },
      });
      throw new ActionableError({
        goal: `Read data file: ${relPath}`,
        problem: isEnoent
          ? `File not found: ${absPath}`
          : `Read failed: ${String(err)}`,
        location: `storage/readDataFile → readDataFile(${relPath})`,
        nextSteps: [
          'Verify the file exists in the data root',
          'Check AI_TRIAD_DATA_ROOT points to the correct data directory',
        ],
      });
    }
  } else {
    const result = await getBackend().readBinaryFile(absPath);
    if (result === null) {
      getGlobalRecorder()?.record({
        type: 'data_read_empty',
        component: 'read-data-file',
        level: 'error',
        message: `readDataFile: missing: ${relPath}`,
        data: { relPath, absPath },
      });
      throw new ActionableError({
        goal: `Read data file: ${relPath}`,
        problem: `File not found: ${absPath}`,
        location: `storage/readDataFile → readDataFile(${relPath})`,
        nextSteps: [
          'Verify the file exists in the data root',
          'Check AI_TRIAD_DATA_ROOT points to the correct data directory',
        ],
      });
    }
    buf = result;
  }

  if (buf.length === 0) {
    getGlobalRecorder()?.record({
      type: 'data_read_empty',
      component: 'read-data-file',
      level: 'error',
      message: `readDataFile: empty buffer: ${relPath}`,
      data: { relPath, absPath },
    });
    throw new ActionableError({
      goal: `Read data file: ${relPath}`,
      problem: `File read returned empty buffer: ${absPath}`,
      location: `storage/readDataFile → readDataFile(${relPath})`,
      nextSteps: [
        'Verify the file is non-empty in the data root',
        'Check that the data precomputation step completed successfully',
      ],
    });
  }

  if (opts?.validate) {
    try {
      opts.validate(buf);
    } catch (err: unknown) {
      getGlobalRecorder()?.record({
        type: 'data_read_empty',
        component: 'read-data-file',
        level: 'error',
        message: `readDataFile: validation failed: ${relPath}`,
        data: { relPath, absPath, error: String(err) },
      });
      throw new ActionableError({
        goal: `Read data file: ${relPath}`,
        problem: `File content failed validation: ${String(err)}`,
        location: `storage/readDataFile → readDataFile(${relPath})`,
        nextSteps: [
          'Verify the file was generated by the expected precomputation step',
          'Check for a stale or truncated file (t/3085)',
        ],
      });
    }
  }

  return buf;
}
