// Copyright (c) 2026 Jeffrey Snover. All rights reserved.
// Licensed under the MIT License. See LICENSE file in the project root.

import { z } from 'zod';
// POV_KEYS = ['accelerationist', 'safetyist', 'skeptic'] — full strings, not short-codes.
// z.enum([...POV_KEYS]) therefore rejects 'acc'/'saf'/'skp' at parse time.
import { POV_KEYS } from '../debate/types.js';
import { ActionableError } from '../debate/errors.js';
import type { OpEdSet } from './types.js';

export const PovKeySchema = z.enum([...POV_KEYS]);

export const OpEdParamsSchema = z.object({
  outlet: z.string().optional(),
  wordCount: z.number().int(),
  newsHook: z.string().optional(),
  thesis: z.string().optional(),
  authorBio: z.string().optional(),
  model: z.string(),
});

export const OpEdGroundingRefSchema = z.object({
  node_id: z.string(),       // snake_case — rejects PS PascalCase "Id"
  label: z.string(),
  category: z.string(),
  pov: PovKeySchema,         // full PovKey — rejects PS short-code "acc"/"saf"/"skp"
  relevance: z.string(),     // snake_case — rejects PS "Relevance"
  how_reflected: z.string(), // snake_case — rejects PS "HowReflected"
});

export const OpEdMemberSchema = z.object({
  pov: PovKeySchema,
  status: z.enum(['complete', 'failed', 'cancelled']),
  // Content fields are optional with defaults so failed/cancelled members
  // (which may have these absent in persisted legacy data) pass the parse.
  // After .default(), the inferred type is still string/number — matches OpEdMember.
  headline: z.string().optional().default(''),
  subtitle: z.string().optional().default(''),
  body: z.string().optional().default(''),
  pitch: z.string().optional(),
  wordCount: z.number().int().optional().default(0),
  grounding: z.array(OpEdGroundingRefSchema),
});

export const OpEdSetSchema = z.object({
  schema_version: z.literal(1),
  set_id: z.string(),
  topic: z.string(),
  params: OpEdParamsSchema,
  created_at: z.string(),
  opeds: z.array(OpEdMemberSchema),
});

/**
 * Parse and validate a raw (unknown) value as an OpEdSet.
 * Throws ActionableError naming the first offending field if validation fails.
 * Use at persist sites (opedIO, opedStore) to catch shape violations at write time.
 */
export function parseOpEdSet(raw: unknown): OpEdSet {
  const result = OpEdSetSchema.safeParse(raw);
  if (result.success) return result.data as unknown as OpEdSet;
  const first = result.error.issues[0];
  const field = first?.path.join('.') ?? '(unknown)';
  throw new ActionableError({
    goal: 'Persist an op-ed set to storage',
    problem: `OpEdSet validation failed on field "${field}": ${first?.message ?? 'schema mismatch'}`,
    location: 'lib/oped/schemas.ts — parseOpEdSet',
    nextSteps: [
      'Check that the op-ed was generated by the TS core (lib/oped/generate.ts) or a conforming PS path.',
      'If data came from an older PS run, verify pov is a full PovKey (not a short-code) and grounding fields use snake_case.',
    ],
  });
}
