// @vitest-environment node
// Copyright (c) 2026 Jeffrey Snover. All rights reserved.
// Licensed under the MIT License. See LICENSE file in the project root.

// t/3315 — communityOpedShareStore: projection store for community op-ed public shares.
// TL t/3315#9 condition 1 (LOAD-BEARING): a NEGATIVE test asserting the public copy
// EXCLUDES community_metadata / submitted_by_display / original_id / submitted_at,
// so a future field-add or spread-refactor cannot silently leak submitter identity.
//
// Tests:
//   (1) NEGATIVE: public copy strips all identity/community fields
//   (2) POSITIVE: allowlisted fields are present in the public copy
//   (3) Non-empty guard: throws ActionableError on empty opeds
//   (4) Non-empty guard: throws ActionableError on missing topic
//   (5) assertSafeId rejects unsafe shareId
//   (6) deletePublicCommunityOpEd calls deleteFile (best-effort, no throw on missing)

import { describe, it, expect, vi, beforeEach } from 'vitest';

// ── Mocks (hoisted before imports) ──

const { mockWriteFile, mockDeleteFile, mockReadFile } = vi.hoisted(() => ({
  mockWriteFile: vi.fn().mockResolvedValue(undefined),
  mockDeleteFile: vi.fn().mockResolvedValue(undefined),
  mockReadFile: vi.fn().mockResolvedValue(null),
}));

vi.mock('../storage/fileIO.js', () => ({
  getUserContentBackend: () => ({
    writeFile: mockWriteFile,
    deleteFile: mockDeleteFile,
    readFile: mockReadFile,
  }),
  assertSafeId: (id: string, label: string) => {
    if (!id || id.includes('..') || id.includes('/')) {
      throw new Error(`Unsafe ${label}: ${id}`);
    }
  },
}));

vi.mock('../config.js', () => ({
  resolveDataPath: (p: string) => `/data/${p}`,
  getDataRoot: () => '/data',
}));

vi.mock('../../../../lib/flight-recorder/index.js', () => ({
  getGlobalRecorder: vi.fn().mockReturnValue(null),
}));

import {
  writePublicCommunityOpEd,
  deletePublicCommunityOpEd,
  type CommunityOpEdItem,
} from '../storage/communityOpedShareStore.js';
import { ActionableError } from '../../../../lib/debate/errors.js';

// ── Helpers ──

function makeItem(overrides: Partial<CommunityOpEdItem> = {}): CommunityOpEdItem {
  return {
    schema_version: 1,
    set_id: 'comm-set-1',
    topic: 'AI Safety Perspectives',
    params: { wordCount: 300, model: 'claude-3-5-haiku' },
    created_at: '2026-09-01T00:00:00Z',
    opeds: [{
      pov: 'acc', status: 'complete',
      headline: 'Accelerating Toward Safety',
      subtitle: 'A case for rapid AI development',
      body: 'The body of the op-ed.',
      byline: 'AI Assistant',
      disclosure: 'Generated by AI.',
      rhetorical_meta: '',
      wordCount: 8,
      grounding: [],
    }],
    // Community-specific fields that MUST be stripped
    community_metadata: { review_status: 'approved', reviewer_id: 'admin-99' },
    submitted_by_display: 'Jane Researcher',
    original_id: 'original-set-42',
    submitted_at: '2026-09-02T00:00:00Z',
    ...overrides,
  };
}

// ── Tests ──

describe('communityOpedShareStore (t/3315)', () => {
  beforeEach(() => {
    mockWriteFile.mockClear();
    mockDeleteFile.mockClear();
  });

  // ─── TL condition 1: LOAD-BEARING NEGATIVE test ───────────────────────────

  it('(1) NEGATIVE: public copy NEVER contains community_metadata, submitted_by_display, original_id, submitted_at', async () => {
    const item = makeItem();
    await writePublicCommunityOpEd(item, 'share-abc-123');

    expect(mockWriteFile).toHaveBeenCalledOnce();
    const written = mockWriteFile.mock.calls[0][1] as string;
    const parsed = JSON.parse(written) as Record<string, unknown>;

    // Top-level exclusions — these must NEVER appear in the public copy at rest
    expect(parsed).not.toHaveProperty('community_metadata');
    expect(parsed).not.toHaveProperty('submitted_by_display');
    expect(parsed).not.toHaveProperty('original_id');
    expect(parsed).not.toHaveProperty('submitted_at');
    // Also must not appear in any nested oped member
    for (const oped of (parsed.opeds ?? []) as Record<string, unknown>[]) {
      expect(oped).not.toHaveProperty('community_metadata');
      expect(oped).not.toHaveProperty('submitted_by_display');
      expect(oped).not.toHaveProperty('original_id');
      expect(oped).not.toHaveProperty('submitted_at');
    }
    // Also must not contain raw user identity fields from OpEdSet
    expect(parsed).not.toHaveProperty('set_id');
    expect(parsed).not.toHaveProperty('params');
  });

  // ─── Positive assertion ───────────────────────────────────────────────────

  it('(2) POSITIVE: allowlisted fields are present in the public copy', async () => {
    const item = makeItem();
    await writePublicCommunityOpEd(item, 'share-xyz-456');

    const written = mockWriteFile.mock.calls[0][1] as string;
    const parsed = JSON.parse(written) as Record<string, unknown>;

    expect(parsed.schema_version).toBe(1);
    expect(parsed.shareId).toBe('share-xyz-456');
    expect(parsed.topic).toBe('AI Safety Perspectives');
    expect(parsed.created_at).toBe('2026-09-01T00:00:00Z');
    expect(Array.isArray(parsed.opeds)).toBe(true);
    expect((parsed.opeds as unknown[]).length).toBe(1);
    const oped = (parsed.opeds as Record<string, unknown>[])[0];
    expect(oped.pov).toBe('acc');
    expect(oped.headline).toBe('Accelerating Toward Safety');
    // Internal fields stripped from member too
    expect(oped).not.toHaveProperty('byline');
    expect(oped).not.toHaveProperty('disclosure');
    expect(oped).not.toHaveProperty('grounding');
  });

  // ─── TL condition 4: non-empty guard ─────────────────────────────────────

  it('(3) throws ActionableError when opeds array is empty (ADR-001 guard)', async () => {
    const item = makeItem({ opeds: [] });
    await expect(writePublicCommunityOpEd(item, 'share-empty')).rejects.toThrow(ActionableError);
    expect(mockWriteFile).not.toHaveBeenCalled();
  });

  it('(4) throws ActionableError when topic is missing (ADR-001 guard)', async () => {
    const item = makeItem({ topic: '' });
    await expect(writePublicCommunityOpEd(item, 'share-notopic')).rejects.toThrow(ActionableError);
    expect(mockWriteFile).not.toHaveBeenCalled();
  });

  // ─── Safety and revocation ────────────────────────────────────────────────

  it('(5) rejects unsafe shareId via assertSafeId', async () => {
    await expect(writePublicCommunityOpEd(makeItem(), '../evil')).rejects.toThrow();
    expect(mockWriteFile).not.toHaveBeenCalled();
  });

  it('(6) deletePublicCommunityOpEd calls deleteFile and does not throw on missing', async () => {
    mockDeleteFile.mockRejectedValueOnce(new Error('file not found'));
    await expect(deletePublicCommunityOpEd('share-to-revoke')).resolves.toBeUndefined();
    expect(mockDeleteFile).toHaveBeenCalledOnce();
  });
});
