// @vitest-environment node
//
// t/2727 — op-ed public-share projection (the info-leak control). projectPublicOpEd
// is a POSITIVE field allowlist: an OpEdSet laden with generation params (model,
// prompts, thesis, authorBio, newsHook) and grounding internals must project to
// EXACTLY the public wire shape and nothing more. This is what guarantees no private
// field is ever written to the public copy at rest.
//
// t/3488 (SO-fixed contract t/3487#1, TL amendment t/3488#2) — BDI grounding is now
// EMBEDDED in the public projection: per-member grounding[] refs pass through, plus a
// top-level grounding_nodes{} map of resolved five-field snapshots and a grounded_at
// timestamp. Binding SO conditions covered here:
//   (1) exact-keys test on the grounding_nodes snapshot (never spread-then-trim)
//   (2) rewrite-is-replace: a second projection fully replaces grounding_nodes{}
//   (3) unresolvable refs (incl. sit-* and unreadable taxonomy files) WARN + skip
//   (4) grounded_at present top-level

import { describe, it, expect, vi, beforeEach } from 'vitest';

const { serverWarn, mockReadTaxonomyFile } = vi.hoisted(() => ({
  serverWarn: vi.fn(),
  mockReadTaxonomyFile: vi.fn(),
}));

vi.mock('../logger.js', () => ({
  log: {
    api: { info: vi.fn(), warn: vi.fn(), error: vi.fn(), debug: vi.fn() },
    server: { info: vi.fn(), warn: serverWarn, error: vi.fn(), debug: vi.fn() },
  },
  getRequestId: () => 'req-test',
  LOG_MAX_LINE_BYTES: 65536,
  writeFramedNdjson: vi.fn(),
}));

vi.mock('../storage/fileIO.js', async (importOriginal) => {
  const actual = await importOriginal<Record<string, unknown>>();
  return { ...actual, readTaxonomyFile: mockReadTaxonomyFile };
});

import { projectPublicOpEd } from '../storage/opedShareStore.js';
import type { OpEdSet } from '../../../../lib/oped/types.js';

const ACC_NODE = { id: 'acc-beliefs-095', label: 'Speed of iteration', description: 'A'.repeat(400), graph_attributes: {} };
const SIT_NODE = { id: 'sit-004', label: 'Model release cadence', description: 'Short situation description.' };

function taxonomyFixture(fileKey: string): unknown {
  if (fileKey === 'accelerationist') return { nodes: [ACC_NODE] };
  if (fileKey === 'situations') return { nodes: [SIT_NODE] };
  if (fileKey === 'safetyist' || fileKey === 'skeptic') return { nodes: [] };
  throw new Error(`unexpected fileKey: ${fileKey}`);
}

function makeSet(overrides: Partial<OpEdSet> = {}): OpEdSet {
  return {
    schema_version: 1,
    set_id: 'set-private-uuid',
    topic: 'AI liability regimes',
    // Generation params — MUST NOT leak (prompts + model + editorial internals).
    params: {
      outlet: 'NYTimes',
      wordCount: 800,
      model: 'gemini-3.5-flash-lite',
      thesis: 'PRIVATE thesis steering the model',
      authorBio: 'PRIVATE author bio',
      newsHook: 'PRIVATE news hook',
    },
    created_at: '2026-08-17T00:00:00Z',
    opeds: [
      {
        pov: 'accelerationist',
        status: 'complete',
        headline: 'The case for speed',
        subtitle: 'Why caution costs lives',
        body: 'Full essay body text.',
        byline: 'AI Assistant',
        disclosure: 'Generated by AI.',
        rhetorical_meta: '',
        wordCount: 812,
        grounding: [
          { node_id: 'acc-beliefs-095', label: 'internal', category: 'beliefs', pov: 'accelerationist', relevance: '0.9', how_reflected: 'internal note' },
        ],
      },
    ],
    ...overrides,
  } as unknown as OpEdSet;
}

describe('projectPublicOpEd — positive allowlist (info-leak guard, t/2727 + t/3488)', () => {
  beforeEach(() => {
    serverWarn.mockClear();
    mockReadTaxonomyFile.mockReset();
    mockReadTaxonomyFile.mockImplementation((fileKey: string) => Promise.resolve(taxonomyFixture(fileKey)));
  });

  it('returns EXACTLY the public top-level keys and nothing else', async () => {
    const pub = await projectPublicOpEd(makeSet(), 'share-xyz');
    expect(Object.keys(pub).sort()).toEqual(
      ['schema_version', 'shareId', 'topic', 'outlet', 'created_at', 'opeds', 'grounding_nodes', 'grounded_at'].sort(),
    );
    expect(pub.schema_version).toBe(2);
    // The public URL key replaces the private storage set_id.
    expect(pub.shareId).toBe('share-xyz');
    expect(pub).not.toHaveProperty('set_id');
    expect(pub).not.toHaveProperty('params');
  });

  it('per-voice members carry EXACTLY the public fields, including pass-through grounding refs', async () => {
    const pub = await projectPublicOpEd(makeSet(), 'share-xyz');
    expect(pub.opeds).toHaveLength(1);
    expect(Object.keys(pub.opeds[0]).sort()).toEqual(
      ['pov', 'status', 'headline', 'subtitle', 'body', 'wordCount', 'grounding'].sort(),
    );
    expect(pub.opeds[0].grounding).toEqual([
      { node_id: 'acc-beliefs-095', label: 'internal', category: 'beliefs', pov: 'accelerationist', relevance: '0.9', how_reflected: 'internal note' },
    ]);
  });

  it('leaks NONE of the private generation params anywhere in the serialized output', async () => {
    const serialized = JSON.stringify(await projectPublicOpEd(makeSet(), 'share-xyz'));
    for (const forbidden of [
      'set-private-uuid',              // storage set_id
      'PRIVATE thesis',                // params.thesis
      'PRIVATE author bio',            // params.authorBio
      'PRIVATE news hook',             // params.newsHook
      'gemini-3.5-flash-lite',         // params.model
    ]) {
      expect(serialized).not.toContain(forbidden);
    }
  });

  it('carries the public-safe fields verbatim (topic, outlet, essay content)', async () => {
    const pub = await projectPublicOpEd(makeSet(), 'share-xyz');
    expect(pub.topic).toBe('AI liability regimes');
    expect(pub.outlet).toBe('NYTimes'); // editorial context is public-safe
    expect(pub.created_at).toBe('2026-08-17T00:00:00Z');
    expect(pub.opeds[0].headline).toBe('The case for speed');
    expect(pub.opeds[0].wordCount).toBe(812);
  });

  it('outlet is null when params carry no outlet', async () => {
    const noOutlet = makeSet({ params: { ...makeSet().params, outlet: undefined } } as unknown as Partial<OpEdSet>);
    const pub = await projectPublicOpEd(noOutlet, 's');
    expect(pub.outlet).toBeNull();
  });

  // ─── SO cond 1: exact five-field pick on grounding_nodes ─────────────────────

  it('(SO cond 1) grounding_nodes snapshot has EXACTLY the five allowlisted keys', async () => {
    const pub = await projectPublicOpEd(makeSet(), 'share-xyz');
    const snap = pub.grounding_nodes['acc-beliefs-095'];
    expect(snap).toBeDefined();
    expect(Object.keys(snap).sort()).toEqual(['id', 'label', 'pov', 'category', 'description_excerpt'].sort());
    expect(snap.id).toBe('acc-beliefs-095');
    expect(snap.label).toBe('Speed of iteration');
    expect(snap.pov).toBe('accelerationist');
    expect(snap.category).toBe('beliefs');
    // description was 400 chars — must be capped, never a raw {...node} spread.
    expect(snap.description_excerpt.length).toBeLessThan(400);
    expect(snap.description_excerpt.endsWith('…')).toBe(true);
    expect(snap).not.toHaveProperty('graph_attributes');
  });

  it('resolves sit-* grounding refs from the situations file (t/3488#2 TL amendment)', async () => {
    const set = makeSet({
      opeds: [{
        ...makeSet().opeds[0],
        grounding: [
          { node_id: 'sit-004', label: 'internal', category: 'situation', pov: 'accelerationist', relevance: '0.8', how_reflected: 'ref' },
        ],
      }],
    } as unknown as Partial<OpEdSet>);
    const pub = await projectPublicOpEd(set, 'share-sit');
    expect(mockReadTaxonomyFile).toHaveBeenCalledWith('situations');
    expect(pub.grounding_nodes['sit-004']).toEqual({
      id: 'sit-004',
      label: 'Model release cadence',
      pov: 'accelerationist',
      category: 'situation',
      description_excerpt: 'Short situation description.',
    });
  });

  // ─── SO cond 2: rewrite-is-replace (the takedown path) ───────────────────────

  it('(SO cond 2) a second projection fully REPLACES grounding_nodes — no merge', async () => {
    const first = await projectPublicOpEd(makeSet(), 'share-xyz');
    expect(first.grounding_nodes).toHaveProperty('acc-beliefs-095');

    const secondSet = makeSet({
      opeds: [{
        ...makeSet().opeds[0],
        grounding: [
          { node_id: 'sit-004', label: 'internal', category: 'situation', pov: 'accelerationist', relevance: '0.5', how_reflected: 'ref' },
        ],
      }],
    } as unknown as Partial<OpEdSet>);
    const second = await projectPublicOpEd(secondSet, 'share-xyz');
    expect(second.grounding_nodes).not.toHaveProperty('acc-beliefs-095');
    expect(second.grounding_nodes).toHaveProperty('sit-004');
  });

  // ─── SO cond 3: unresolvable refs WARN + skip, never fail the whole write ────

  it('(SO cond 3) an unresolvable ref (node id not in the taxonomy file) is WARNed and OMITTED', async () => {
    const set = makeSet({
      opeds: [{
        ...makeSet().opeds[0],
        grounding: [
          { node_id: 'acc-beliefs-999-retired', label: 'internal', category: 'beliefs', pov: 'accelerationist', relevance: '0.5', how_reflected: 'ref' },
        ],
      }],
    } as unknown as Partial<OpEdSet>);
    const pub = await projectPublicOpEd(set, 'share-retired');
    expect(pub.grounding_nodes).not.toHaveProperty('acc-beliefs-999-retired');
    expect(pub.schema_version).toBe(2); // projection still succeeds
    const call = serverWarn.mock.calls.find(([ctx]: [{ cause?: string }]) => ctx?.cause === 'grounding-node-unresolvable');
    expect(call).toBeDefined();
    expect(call?.[0]?.node_id).toBe('acc-beliefs-999-retired');
  });

  it('(SO cond 3) an unreadable taxonomy backing file is WARNed and its refs are skipped, not thrown', async () => {
    mockReadTaxonomyFile.mockImplementation((fileKey: string) => {
      if (fileKey === 'accelerationist') return Promise.reject(new Error('ENOENT'));
      return Promise.resolve(taxonomyFixture(fileKey));
    });
    const pub = await projectPublicOpEd(makeSet(), 'share-unreadable');
    expect(pub.grounding_nodes).not.toHaveProperty('acc-beliefs-095');
    const call = serverWarn.mock.calls.find(([ctx]: [{ cause?: string }]) => ctx?.cause === 'grounding-taxonomy-file-unreadable');
    expect(call).toBeDefined();
  });

  // ─── SO cond 4: grounded_at snapshot timestamp ───────────────────────────────

  it('(SO cond 4) grounded_at is present as an ISO timestamp', async () => {
    const pub = await projectPublicOpEd(makeSet(), 'share-xyz');
    expect(typeof pub.grounded_at).toBe('string');
    expect(() => new Date(pub.grounded_at).toISOString()).not.toThrow();
  });
});
